# Create a "deploy new service" workflow
AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::LanguageExtensions'
Parameters:
  WorkflowResources:
    Description: "Shared permissions across workflow resources"
    Type: "String"
    MinLength: 1 # pseudo required
    # MaxLength: 255,
    # AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$",
    Default: "WorkflowResources"
Resources:
  deployApplicationServiceWorkflow:
    Type: AWS::StepFunctions::StateMachine
    Properties: 
      DefinitionString: 
        Fn::ToJsonString: {
          "Comment": "A simple AWS Step Functions state machine that automates a call center support session.",
          "StartAt": "Validate Service Spec",
          "States": {
              "Validate Service Spec": {
                  "Type": "Task",
                  "Resource": !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mast-lambda",
                  "Parameters": {
                      "step_name": "validate_service_spec",
                      "service_spec_json.$": "$.service_spec_json",
                      "environment.$": "$.environment",
                      "global_state.$": "$.global_state"
                  },
                  "Next": "Create ECS Task Definition"
              },
              "Create ECS Task Definition": {
                  "Type": "Task",
                  "Resource": !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mast-lambda",
                  "Parameters": {
                      "step_name": "lambda_create_ecs_task_definition",
                      "service_spec_json.$": "$.service_spec_json",
                      "environment.$": "$.environment",
                      "output_file": "/tmp/deployment.json",
                      "service_spec_url": "https://raw.githubusercontent.com/yahooo",
                      "global_state.$": "$.global_state"
                  },
                  "Next": "Create ELB Target Groups"
              },
              "Create ELB Target Groups": {
                  "Type": "Task",
                  "Resource": !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mast-lambda",
                  "Parameters": {
                      "step_name": "create_elb_target_groups",
                      "service_spec_json.$": "$.service_spec_json",
                      "environment.$": "$.environment",
                      "global_state.$": "$.global_state"
                  },
                  "Next": "Update ELB Listener Rules"
              },
              "Update ELB Listener Rules": {
                  "Type": "Task",
                  "Resource": !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mast-lambda",
                  "Parameters": {
                      "step_name": "update_elb_listener_rules",
                      "service_spec_json.$": "$.service_spec_json",
                      "environment.$": "$.environment",
                      "global_state.$": "$.global_state"
                  },
                  "Next": "Create ECS Service"
              },
              "Create ECS Service": {
                  "Type": "Task",
                  "Resource": !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:mast-lambda",
                  "Parameters": {
                      "step_name": "lambda_create_ecs_service",
                      "service_spec_json.$": "$.service_spec_json",
                      "environment.$": "$.environment",
                      "poll_interval": 10,
                      "task_definition_arn.$": "$.global_state.task_definition_arn",
                      "output_file": "/tmp/deployment.json",
                      "global_state.$": "$.global_state"
                  },
                  "End": true
              }
          }
      }
      RoleArn: { "Fn::ImportValue": { "Fn::Sub": "${WorkflowResources}-RoleArn" } }
      StateMachineName: DeployServiceALB
