Parameters:
  TemplateBucketName:
    Description: "Bucket name where the templates are uploaded"
    Type: "String"
    MinLength: 1 # pseudo required
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
Resources:
  SharedWorkflowResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucketName}/WORKFLOW_RESOURCES.yaml
      TimeoutInMinutes: "60"
      Parameters:
        PolicyName: "default-step-function-lambda-role-policy"
        RoleName: "default-step-function-lambda-role"
  WorkflowExecutor:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucketName}/EXECUTE_WORKFLOW.yaml
      TimeoutInMinutes: "60"
      Parameters:
        WorkflowRoleArn: !GetAtt SharedWorkflowResources.Outputs.RoleArn
